[package]
name = "gfx-backend-vulkan"
version = "0.6.5"
description = "Vulkan API backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "MIT OR Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx-backend-vulkan"
workspace = "../../.."
edition = "2018"

[features]
default = []
use-rtld-next = ["shared_library"]

[lib]
name = "gfx_backend_vulkan"

[dependencies]
arrayvec = "0.5"
byteorder = "1"
log = { version = "0.4" }
shared_library = { version = "0.1.9", optional = true }
ash = { git = "https://github.com/MaikKlein/ash", rev = "3703e73d304e840f0ee36d1ed369473c8d7c252a" }
hal = { path = "../../hal", version = "0.6", package = "gfx-hal" }
parking_lot = "0.11"
smallvec = "1.0"
raw-window-handle = "0.3"
inplace_it = "0.3.2"

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-6"
features = ["spv-out"]
optional = true

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["libloaderapi", "windef", "winuser"] }
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.5"
core-graphics-types = "0.1"

